language: generic

env:
  - PYTHON_VERSION=3.7
os:
  - linux
  - osx

branches:
  - master

services:
  - docker

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      curl -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
    fi
  # More conda setup to get miniconda in and a virtual env. setup
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda=4.8.2
  - conda info -a   # Useful for debugging any issues with conda
  # Create the env

install:
  # Install dependencies
  - conda config --remove channels defaults
  - conda env create -f environment.yml --name test_env python=$PYTHON_VERSION
  - source activate test_env
  # Development installation
  - conda install pip setuptools
  - conda install -c anaconda pytest pytest-cov
  - conda install -c conda-forge nbsphinx
  - pip install coveralls travis-sphinx


script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ];
        then
          pytest tests/linux/;
      elif [ "$TRAVIS_OS_NAME" == "osx"  ];
        then
          pytest tests/osx/;
      else
        echo "Invalid OS";
      fi

after_success:
  # Code Coverage
  - coveralls
  # Anaconda Upload
  - conda deactivate
  - conda install conda-build anaconda-client
  - conda config --set anaconda_upload no
  # - conda build recipe -q
  # - builddir=(`conda build recipe --output`)
  - |
    if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
        conda config --set anaconda_upload yes;
        conda build --token $CONDA_UPLOAD_TOKEN --python $PYTHON_VERSION -c CANIS-LAB recipe;
    fi
  # # Docs to gh-pages
  # - source activate test_env  # Reactivate the env to have all deps installed.
  # - travis-sphinx build --source=docs --nowarn # The sphinx build script
  # - travis-sphinx deploy --branches=master
