name: pypack
channels:
  - conda-forge
dependencies:
  - python=3.7
  - fiona=1.8.7
  - geopandas=0.6.1
  - pandas=0.25.1
  - gdal=2.4.2
  - folium
  - imageio
  - beautifulsoup4
  - urllib3
  - pyqt
  - tqdm
  - shapely
  - matplotlib
  - pip=19.3.1
  - pip:
    - mordecai
    - pyqtgraph
    - docker
