name: pypack
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - geopandas=0.6.1
  - folium
  - beautifulsoup4
  - urllib3
  - pyqt
  - tqdm
  - shapely
  - imageio
  - matplotlib
  - pip
  - pip:
    - pyqtgraph
    - docker
    - mordecai
