name: pypack
channels:
  - conda-forge
dependencies:
  - python=3.7
  - fiona
  - geopandas
  - pandas
  - folium
  - imageio
  - beautifulsoup4
  - urllib3
  - pyqt
  - tqdm
  - shapely
  - matplotlib
  - pip
  - pip:
    - mordecai
    - pyqtgraph
    - docker
