name: pypack
channels:
  - conda-forge
dependencies:
  - python=3.7
  - beautifulsoup4
  - urllib3
  - pandas
  - geopandas
  - folium
  - pyqt
  - tqdm
  - shapely
  - matplotlib
  - imageio=2.8.0
  - descartes
  - pip
  - pip:
    - mordecai
    - keras==2.3.1
    - pyqtgraph
    - docker
