name: pypack
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - pandas
  - geopandas
  - folium
  - beautifulsoup4
  - urllib3
  - pyqt
  - tqdm
  - shapely
  - imageio
  - matplotlib
  - pip
  - pip:
    - pyqtgraph
    - mordecai
    - docker
    - spacy
